apiVersion: v1
kind: Service
metadata:
  name: sidecar-demo-svc
spec:
  selector:
    app: sidecar-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080   # Range: 30000-32767
  type: NodePort